export interface Country {
  code: string;
  name: string;
}

// Guinée en tête (contexte principal de déploiement), puis reste du monde par ordre alphabétique.
export const COUNTRIES: Country[] = [
  { code: 'GN', name: 'Guinée' },
  { code: 'SN', name: 'Sénégal' },
  { code: 'ML', name: 'Mali' },
  { code: 'CI', name: "Côte d'Ivoire" },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'NE', name: 'Niger' },
  { code: 'MR', name: 'Mauritanie' },
  { code: 'GM', name: 'Gambie' },
  { code: 'GW', name: 'Guinée-Bissau' },
  { code: 'SL', name: 'Sierra Leone' },
  { code: 'LR', name: 'Liberia' },
  { code: 'GH', name: 'Ghana' },
  { code: 'NG', name: 'Nigeria' },
  { code: 'CM', name: 'Cameroun' },
  { code: 'TD', name: 'Tchad' },
  { code: 'TG', name: 'Togo' },
  { code: 'BJ', name: 'Bénin' },
  { code: 'GA', name: 'Gabon' },
  { code: 'CG', name: 'Congo' },
  { code: 'CD', name: 'RD Congo' },
  { code: 'MA', name: 'Maroc' },
  { code: 'DZ', name: 'Algérie' },
  { code: 'TN', name: 'Tunisie' },
  { code: 'LY', name: 'Libye' },
  { code: 'EG', name: 'Égypte' },
  { code: 'SD', name: 'Soudan' },
  { code: 'DJ', name: 'Djibouti' },
  { code: 'SO', name: 'Somalie' },
  { code: 'KE', name: 'Kenya' },
  { code: 'TZ', name: 'Tanzanie' },
  { code: 'ZA', name: 'Afrique du Sud' },
  { code: 'SA', name: 'Arabie Saoudite' },
  { code: 'AE', name: 'Émirats Arabes Unis' },
  { code: 'QA', name: 'Qatar' },
  { code: 'KW', name: 'Koweït' },
  { code: 'TR', name: 'Turquie' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'ID', name: 'Indonésie' },
  { code: 'MY', name: 'Malaisie' },
  { code: 'FR', name: 'France' },
  { code: 'BE', name: 'Belgique' },
  { code: 'CH', name: 'Suisse' },
  { code: 'DE', name: 'Allemagne' },
  { code: 'GB', name: 'Royaume-Uni' },
  { code: 'ES', name: 'Espagne' },
  { code: 'IT', name: 'Italie' },
  { code: 'NL', name: 'Pays-Bas' },
  { code: 'CA', name: 'Canada' },
  { code: 'US', name: 'États-Unis' },
];
